pygments: true
permalink: /posts/:title

name: Waldemar Quevedo
url: http://wallyqs.github.io
description: A place to share some Org texts
twitter: wallyqs
github: wallyqs
gravatar_url: http://gravatar.com/avatar/210dbb68c0380da4d77ff46759f02d1a
