# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Literate Infrastructure
tagline:          'PaaS + Org mode'
description:      '<a href="https://twitter.com/wallyqs" target="_blank">@wallyqs</a>'
baseurl:          /

author:
  name:           'Waldemar Quevedo'
  url:            https://twitter.com/wallyqs

paginate:         5
