# TODO: Use Org mode for this too

# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Literate Infrastructure
tagline:          'PaaS + Org mode'
description:      'written by <a href="https://twitter.com/mdo" target="_blank">@wallyqs</a>.'
baseurl:          /

author:
  name:           'Waldemar Quevedo'
  url:            https://twitter.com/wallyqs

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/wallyqs/org-hyde
